# Generated by Django 4.0.4 on 2022-05-29 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ror', '0003_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_image',
            field=models.ImageField(upload_to='static/images'),
        ),
    ]
